name: "Fossa Licenses Check"

on:
  pull_request:
    paths:
        - "Pipfile.lock"
        - ".github/workflows/fossa.yaml"
  push:
    branches:
      - main
    paths:
      - "Pipfile.lock"
      - ".github/workflows/fossa.yaml"

jobs:
  fossa:
    runs-on: "ubuntu-22.04"
    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: "Install fossa"
        run: |
          wget -q -P /tmp https://github.com/fossas/fossa-cli/releases/download/v3.4.5/fossa_3.4.5_linux_amd64.zip
          cd /usr/local/bin
          unzip /tmp/fossa_*.zip
      - name: print fossa analyze options
        run: fossa analyze --help
      - name: "Install packages"
        run: "sudo apt-get update; sudo apt-get -y install libcurl4-openssl-dev"
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
          cache: "pipenv"
          cache-dependency-path: "Pipfile.lock"
      - name: "Install pipenv"
        run: "pip install pipenv wheel"
      - name: "Install dependencies"
        run: "pipenv sync --dev"
      - name: "Run fossa analyze"
        run: "fossa analyze -b $BRANCH"
